name: Perform Benchmarks

on: push
   # branches:
     # - main
     # - develop
  #pull_request:
   # branches:
   #   - main
    #  - develop


concurrency:
  group: benchmarks-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true


env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"
  BRANCH_NAME: ${{ github.base_ref || github.ref_name }}
  PUSH_TO_BENCHMARKS: false

jobs:
  benchmark-then-upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/create-github-app-token@v2
      id: tudo-seal-workflow-token
      with:
        app-id: ${{ secrets.TUDO_SEAL_WORKFLOW_CLIENT_ID}}
        private-key: ${{ secrets.TUDO_SEAL_WORKFLOW_PRIVATE_KEY }}

    - uses: actions/checkout@v4
      with:
        # Full history for timestamps
        fetch-depth: 0
        token: ${{ steps.tudo-seal-workflow-token.outputs.token }}

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: Install Hatch
      uses: pypa/hatch@install

    - name: Run Benchmark Suite
      run: hatch test benchmarks --benchmark-json benchmarks.json

    - name: XDTesting Print Directory Structure
      uses: FiorelaCiroku/XDTesting-Print-Directory-Structure@v1.0.2

    - uses: actions/checkout@v4
      with:
        repository: tudo-seal/cosy-benchmarks
        token: ${{ steps.tudo-seal-workflow-token.outputs.token }}
        ref: 'gh-pages'
        path: 'cosy-benchmarks'

    - name: Store Benchmark Result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        name: Python Benchmark with pytest-benchmark
        tool: 'pytest'
        output-file-path: benchmarks.json
        github-token: ${{ steps.tudo-seal-workflow-token.outputs.token }}
        auto-push: false
        alert-threshold: '300%'
        comment-on-alert: true
        fail-on-alert: true
        comment-always: true
        gh-repository: 'github.com/tudo-seal/cosy-benchmarks'
        benchmark-data-dir-path: '${{ env.BRANCH_NAME }}/benchmarks'

    - name: Push Benchmark Results
      # if: github.event_name != 'pull_request'
      run: |
        git config user.name "tudo-seal-workflows[bot]"
        git config user.email "244727884+tudo-seal-workflows[bot]@users.noreply.github.com"
        git commit --amend --reset-author --no-edit
        git push 'https://tudo-seal-workflows[bot]:${{ steps.tudo-seal-workflow-token.outputs.token }}@github.com/tudo-seal/cosy-benchmarks.git' gh-pages:gh-pages
      env:
        GH_TOKEN: ${{ steps.tudo-seal-workflow-token.outputs.token }}