name: Perform Benchmarks

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop


concurrency:
  group: benchmarks-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true


env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"
  BRANCH_NAME: ${{ github.base_ref || github.ref_name }}
  PUSH_TO_BENCHMARKS: false
  COMMENT_ALWAYS: true

jobs:
  benchmark-then-upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/create-github-app-token@v2
      if: ${{ ! github.event.pull_request.head.repo.fork && github.actor != 'dependabot[bot]' }}
      id: tudo-seal-workflow-token
      with:
        app-id: ${{ secrets.TUDO_SEAL_WORKFLOW_CLIENT_ID }}
        private-key: ${{ secrets.TUDO_SEAL_WORKFLOW_PRIVATE_KEY }}
        repositories: |
          cosy
          cosy-benchmarks

    - uses: actions/checkout@v5
      with:
        repository: tudo-seal/cosy-benchmarks
        token: ${{ steps.tudo-seal-workflow-token.outputs.token }}
        ref: 'gh-pages'

    - uses: actions/checkout@v5
      with:
        # Full history for timestamps
        fetch-depth: 0
        token: ${{ steps.tudo-seal-workflow-token.outputs.token }}
        path: 'cosy-nested'

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: Install Hatch
      uses: pypa/hatch@install

    - name: Run Benchmark Suite
      run: hatch test benchmarks --benchmark-json benchmarks.json
      working-directory: 'cosy-nested'

    - name: Config Git
      run: |
        git config user.name "tudo-seal-workflows[bot]"
        git config user.email "244727884+tudo-seal-workflows[bot]@users.noreply.github.com"

    - name: Determine Push Or Not
      if: github.event_name != 'pull_request'
      run: |
        echo "PUSH_TO_BENCHMARKS=true" >> $GITHUB_ENV
        echo "COMMENT_ALWAYS=false" >> $GITHUB_ENV

    - name: Store Benchmark Result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        name: Benchmark CoSy
        tool: 'pytest'
        output-file-path: cosy-nested/benchmarks.json
        github-token: ${{ (github.event.pull_request.head.repo.fork && github.actor != 'dependabot[bot]') && secrets.GITHUB_TOKEN  || steps.tudo-seal-workflow-token.outputs.token }}
        auto-push: ${{ env.PUSH_TO_BENCHMARKS }}
        alert-threshold: '300%'
        comment-on-alert: true
        fail-on-alert: true
        comment-always: ${{ env.COMMENT_ALWAYS }}
        summary-always: true
        gh-repository: 'github.com/tudo-seal/cosy-benchmarks'
        benchmark-data-dir-path: '${{ env.BRANCH_NAME }}/benchmarks'