name: Perform Checks

on:
  workflow_call:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop


concurrency:
  group: checks-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true


env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"
  BRANCH_NAME: ${{ github.base_ref || github.ref_name }}

jobs:
  test-lint-type-coverage:
    name: Python ${{ matrix.python-version }} on ${{ startsWith(matrix.os, 'macos-') && 'macOS' || startsWith(matrix.os, 'windows-') && 'Windows' || 'Linux' }}
    runs-on: ${{ matrix.os }}
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Hatch
      uses: pypa/hatch@install

    - name: Run static analysis
      run: hatch fmt --check

    - name: Run type checks
      run: hatch run types:check

    - name: Run tests
      run: hatch test tests --python ${{ matrix.python-version }} --cov --cov-branch --cov-report=xml --randomize --parallel --junit-xml=report.xml

    - name: Upload Tests to Codecov
      if: ${{ !cancelled() && !contains( github.head_ref, 'hotfix/')}}
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./report.xml
        report_type: test_results
        flags: ${{ matrix.os }}-${{ matrix.python-version }}

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v5
      if: ${{ !contains( github.head_ref, 'hotfix/') }}
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        flags: ${{ matrix.os }}-${{ matrix.python-version }}

    - name: Run Benchmark Suite
      run: hatch test benchmarks --benchmark-json benchmarks.json

    - uses: actions/create-github-app-token@v2
      id: tudo-seal-workflow-token
      with:
        app-id: ${{ secrets.TUDO_SEAL_WORKFLOW_CLIENT_ID}}
        private-key: ${{ secrets.TUDO_SEAL_WORKFLOW_PRIVATE_KEY }}

    - name: Store Benchmark Result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        name: Python Benchmark with pytest-benchmark
        tool: 'pytest'
        output-file-path: benchmarks.json
        github-token: ${{ steps.tudo-seal-workflow-token.outputs.token }}
        auto-push: false
        alert-threshold: '300%'
        comment-on-alert: true
        fail-on-alert: true
        comment-always: true
        gh-repository: 'github.com/tudo-seal/cosy-benchmarks'
        benchmark-data-dir-path: '${{ env.BRANCH_NAME }}/benchmarks'

    - name: Push Benchmark Results
      if: github.event_name != 'pull_request'
      run: |
        git config user.name "tudo-seal-workflow[bot]"
        git config user.email "244727884+tudo-seal-workflow[bot]@users.noreply.github.com"
        git push 'https://you:${{ steps.tudo-seal-workflow-token.outputs.token }}@github.com/tudo-seal/cosy-benchmarks.git' gh-pages:gh-pages