name: 'Check PR Rules for Main'

on:
  pull_request_target:
    types: [ opened, reopened ]
    branches:
      - main

env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  pr-rules-main:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - uses: actions/create-github-app-token@v2
        id: tudo-seal-workflow-token
        with:
          app-id: ${{ secrets.TUDO_SEAL_WORKFLOW_CLIENT_ID}}
          private-key: ${{ secrets.TUDO_SEAL_WORKFLOW_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          # Full history for timestamps
          fetch-depth: 0
          token: ${{ steps.tudo-seal-workflow-token.outputs.token }}

      - name: Close Pull Request and Comment if Violating
        if: ${{ !contains( github.head_ref, 'feature/') && !contains( github.head_ref, 'bugfix/') && !contains( github.head_ref, 'dependabot/github_actions/')}}
        run: |
          gh pr comment ${{ env.PR_NUMBER }} --body ":warning: You can only merge to main from a release or a hotfix branch. :warning:"
          gh pr close ${{ env.PR_NUMBER }}
        env:
          GH_TOKEN: ${{ steps.tudo-seal-workflow-token.outputs.token }}

      - name: Fail Job if Violating
        if: ${{ !contains( github.head_ref, 'release/') && !contains( github.head_ref, 'hotfix/')}}
        run: |
          echo "Reason: You can only merge to main from a release or a hotfix branch."
          exit 1
      - name: Succeed Job if not Violating
        if: ${{ contains( github.head_ref, 'release/') || contains( github.head_ref, 'hotfix/')}}
        run: |
          exit 0